# Generated by Django 5.1.7 on 2025-04-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_passwordreset_options_remove_user_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(default='1737e1', max_length=10, unique=True)),
                ('original_url', models.URLField()),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
