# Generated by Django 5.1.7 on 2025-04-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_shortenedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedlink',
            name='short_code',
            field=models.CharField(default='9781ee', max_length=10, unique=True),
        ),
    ]
