# Generated by Django 5.1.7 on 2025-04-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_livestock_type_alter_shortenedlink_short_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedlink',
            name='short_code',
            field=models.CharField(default='1cc666', max_length=10, unique=True),
        ),
    ]
