# Generated by Django 5.1.7 on 2025-04-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_shortenedlink_short_code_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedlink',
            name='short_code',
            field=models.CharField(default='739254', max_length=10, unique=True),
        ),
    ]
