# Generated by Django 5.1.7 on 2025-04-10 07:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_shortenedlink_short_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='entry_time',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shortenedlink',
            name='short_code',
            field=models.CharField(default='93ead9', max_length=10, unique=True),
        ),
    ]
