# Generated by Django 5.1.7 on 2025-04-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_entry_time_otp_created_at_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedlink',
            name='short_code',
            field=models.CharField(default='5d8053', max_length=10, unique=True),
        ),
    ]
