# Generated by Django 5.1.7 on 2025-04-08 08:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('Feed', 'Feed'), ('Livestock', 'Livestock')], max_length=255)),
                ('item_id', models.UUIDField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('record_type', models.CharField(choices=[('Sale', 'Sale'), ('Expense', 'Expense')], max_length=255)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale & Expense',
                'verbose_name_plural': 'Sales & Expenses',
                'ordering': ('-entry_date',),
            },
        ),
    ]
