# Generated by Django 5.1.7 on 2025-03-24 19:17

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Bird Feed', 'Bird Feed'), ('Fish Feed', 'Fish Feed')], default='Bird Feed', max_length=15)),
                ('action', models.CharField(choices=[('Bought', 'Bought'), ('Consumed', 'Consumed')], default='Bought', max_length=15)),
                ('quantity', models.FloatField()),
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
                ('entry_date', models.DateField(default=datetime.date.today)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feed',
                'verbose_name_plural': 'Feed',
                'ordering': ('-entry_date',),
            },
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Bird', 'Bird'), ('Fish', 'Fish')], default='Bird', max_length=15)),
                ('action', models.CharField(choices=[('Bought', 'Bought'), ('Sold', 'Sold'), ('Dead', 'Dead')], default='Bought', max_length=15)),
                ('quantity', models.PositiveIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('entry_date', models.DateField(default=datetime.date.today)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Livestock',
                'verbose_name_plural': 'Livestock',
                'ordering': ('-entry_date',),
            },
        ),
    ]
