# Generated by Django 5.2 on 2025-04-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockactivity',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=15000, max_digits=10),
            preserve_default=False,
        ),
    ]
