# Generated by Django 5.1.7 on 2025-03-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
