# Generated by Django 5.1.7 on 2025-03-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_feed_cost_alter_livestock_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='entry_date',
            field=models.DateField(),
        ),
    ]
