# Generated by Django 5.2 on 2025-04-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_livestockactivity_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockactivity',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('sold', 'Sold'), ('dead', 'Dead')], max_length=20),
        ),
    ]
