# Generated by Django 5.1.7 on 2025-04-08 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_feed_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='action',
            field=models.CharField(choices=[('Bought', 'Bought'), ('Consumed', 'Consumed')], default='Bought', max_length=255),
        ),
        migrations.AlterField(
            model_name='feed',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(choices=[('Bird Feed', 'Bird Feed'), ('Fish Feed', 'Fish Feed')], default='Bird Feed', max_length=255),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='action',
            field=models.CharField(choices=[('Bought', 'Bought'), ('Sold', 'Sold'), ('Dead', 'Dead')], default='Bought', max_length=255),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='name',
            field=models.CharField(choices=[('Bird', 'Bird'), ('Fish', 'Fish')], default='Bird', max_length=255),
        ),
    ]
