# Generated by Django 5.2 on 2025-04-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_livestockactivity_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedactivity',
            options={'ordering': ('-entry_date',), 'verbose_name': 'Feed Activity', 'verbose_name_plural': 'Feed Activities'},
        ),
        migrations.AlterModelOptions(
            name='livestockactivity',
            options={'ordering': ('-entry_date',), 'verbose_name': 'Livestock Activity', 'verbose_name_plural': 'Livestock Activities'},
        ),
    ]
