# Generated by Django 5.1.7 on 2025-04-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_feed_action_alter_feed_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feed',
            name='action',
            field=models.CharField(choices=[('Bought', 'Bought'), ('Consumed', 'Consumed'), ('Initial', 'Initial')], max_length=100),
        ),
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(choices=[('Poultry Feed', 'Poultry Feed'), ('Fish Feed', 'Fish Feed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='action',
            field=models.CharField(choices=[('Bought', 'Bought'), ('Sold', 'Sold'), ('Dead', 'Dead'), ('Initial', 'Initial')], max_length=100),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='name',
            field=models.CharField(choices=[('Poultry', 'Poultry'), ('Fish', 'Fish')], max_length=100),
        ),
    ]
