# Generated by Django 5.2 on 2025-04-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_feedactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedactivity',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livestockactivity',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedactivity',
            name='action',
            field=models.CharField(choices=[('initial', 'Initial'), ('purchased', 'Purchased'), ('consumed', 'Consumed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='livestockactivity',
            name='action',
            field=models.CharField(choices=[('initial', 'Initial'), ('added', 'Added'), ('sold', 'Sold'), ('dead', 'Dead')], max_length=20),
        ),
    ]
