# Generated by Django 5.1.7 on 2025-04-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_livestock_is_locked_alter_feed_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
