# Generated by Django 5.2 on 2025-04-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='entry_date',
            field=models.DateField(),
        ),
    ]
